from __future__ import annotations

from enum import StrEnum


class ApplicationStatus(StrEnum):
    DISCOVERED = "DISCOVERED"
    ELIGIBLE = "ELIGIBLE"
    QUEUED = "QUEUED"
    TAILORING = "TAILORING"
    READY = "READY"
    APPLYING = "APPLYING"
    SUBMISSION_UNKNOWN = "SUBMISSION_UNKNOWN"
    HUMAN_REQUIRED = "HUMAN_REQUIRED"
    SUBMITTED = "SUBMITTED"
    VERIFIED = "VERIFIED"
    FAILED = "FAILED"
    RETRY_PENDING = "RETRY_PENDING"
    SKIPPED = "SKIPPED"
    CLOSED = "CLOSED"


class JobStatus(StrEnum):
    NEW = "NEW"
    UPDATED = "UPDATED"
    UNCHANGED = "UNCHANGED"
    CLOSED = "CLOSED"


class JobFamily(StrEnum):
    DATA_ANALYTICS = "DATA_ANALYTICS"
    PRODUCT_PM = "PRODUCT_PM"
    BUSINESS_SYSTEMS = "BUSINESS_SYSTEMS"
    FINANCE = "FINANCE"
    TECHNICAL = "TECHNICAL"
    UNKNOWN = "UNKNOWN"


class Persona(StrEnum):
    DATA = "DATA"
    PRODUCT_PM = "PRODUCT_PM"
    BUSINESS_SYSTEMS = "BUSINESS_SYSTEMS"
    FINANCE = "FINANCE"
    TECHNICAL = "TECHNICAL"


class FailureCategory(StrEnum):
    ACCOUNT_CREATION = "ACCOUNT_CREATION"
    LOGIN = "LOGIN"
    CAPTCHA = "CAPTCHA"
    MFA = "MFA"
    RESUME_UPLOAD = "RESUME_UPLOAD"
    FORM_MAPPING = "FORM_MAPPING"
    CUSTOM_QUESTION = "CUSTOM_QUESTION"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    NETWORK = "NETWORK"
    RATE_LIMIT = "RATE_LIMIT"
    ATS_CHANGED = "ATS_CHANGED"
    SUBMISSION_UNKNOWN = "SUBMISSION_UNKNOWN"
    OTHER = "OTHER"


class QuestionAnswerState(StrEnum):
    AUTO_SAFE = "AUTO_SAFE"
    AUTO_FROM_PROFILE = "AUTO_FROM_PROFILE"
    HUMAN_REQUIRED = "HUMAN_REQUIRED"
    UNSUPPORTED = "UNSUPPORTED"
